In [2]:
import pandas as pd
import numpy as np

In [3]:
abiotic_df = pd.read_excel('../data/ABIO.xlsx', sheet_name='ABIO_COMBINED')
biotic_df = pd.read_excel('../data/PHYTO.xlsx', sheet_name='PHYTO_FLATTENED')

display(abiotic_df)

display(biotic_df)

,LOC_CODE,DATUMTIJDWAARDE,ZS,ZICHT,T,SiO2,SALNTT,PO4,pH,NO3,NO2,NH4,E,CHLFa
0,DANTZGT,1-10-2000 09:30:00,26.0,NaN,NaN,12.428571,NaN,1.483871,NaN,1.142857,1.000000,9.500000,NaN,8.00
1,DANTZGT,1-10-2002 09:30:00,NaN,10.0,15.170,NaN,31.18,NaN,8.060,NaN,NaN,NaN,NaN,NaN
2,DANTZGT,1-10-2003 07:11:00,89.0,5.0,13.250,5.821429,33.03,1.354839,8.130,1.214286,0.714286,9.142857,3.23678,20.60
3,DANTZGT,1-10-2009 10:19:00,NaN,NaN,15.000,NaN,31.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DANTZGT,1-10-2010 08:02:00,160.0,3.0,12.400,18.928571,28.90,0.806452,8.000,3.571429,1.642857,15.714286,4.61000,16.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15288,WALCRN70,9-4-1992 09:19:00,5.0,NaN,7.900,0.500000,35.31,0.080645,8.300,3.642857,0.071429,0.642857,NaN,4.64
15289,WALCRN70,9-4-2001 23:16:00,6.0,NaN,8.338,1.035714,34.67,0.129032,8.227,3.142857,0.142857,0.142857,NaN,9.20
15290,WALCRN70,9-6-1994 03:08:00,2.0,NaN,12.100,0.321429,34.83,0.709677,8.500,0.178571,0.035714,0.285714,NaN,2.60
15291,WALCRN70,9-8-1999 19:15:00,2.0,NaN,18.120,1.250000,35.08,0.129032,7.989,0.107143,0.214286,0.500000,NaN,1.18
15292,WALCRN70,9-8-1999 19:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25350,NaN

,LOC_CODE,DATUMTIJDWAARDE,Acn,Aco,Ata,Agl,Cfu,Ccu,Cda,Cdeb,...,Rst,Rte,Stu,Tni,Tec,Tle,Tno,Tro,Tor,Dat
0,DANTZGT,1990-04-04 00:00:00,NaN,NaN,NaN,3.271842,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.669596,3.572755,3.572755,NaN,4.475787,NaN,NaN
1,DANTZGT,1990-04-24 00:00:00,NaN,NaN,NaN,4.590418,NaN,NaN,NaN,NaN,...,NaN,NaN,2.448706,3.447933,NaN,NaN,NaN,3.447933,NaN,NaN
2,DANTZGT,1990-05-09 00:00:00,NaN,NaN,NaN,4.669596,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.012035,1.973128,NaN
3,DANTZGT,1990-05-23 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.590842,NaN,NaN
4,DANTZGT,1990-06-07 00:00:00,NaN,NaN,2.267172,5.300487,2.444045,NaN,NaN,NaN,...,NaN,NaN,NaN,3.566909,1.968483,3.442009,NaN,3.496376,1.968483,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11058,WALCRN70,2019-06-13 00:00:00,NaN,2.034717,NaN,2.333737,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.809514,NaN,NaN,NaN,NaN,2.333737,NaN
11059,WALCRN70,2019-07-15 00:00:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.961517,NaN
11060,WALCRN70,2019-08-15 11:37:00,NaN,2.008643,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.959085,NaN,NaN,NaN,NaN,3.004795,NaN
11061,WALCRN70,2019-09-12 13:29:00,NaN,NaN,NaN,NaN,NaN,2.980947,3.032049,2.980947,...,NaN,NaN,NaN,2.380246,NaN,NaN,NaN,NaN,3.281750,NaN
11062,WALCRN70,2019-10-30 00:00:00,NaN,NaN,NaN,2.708511,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.854396,NaN,NaN,NaN,2.611813,3.905874,NaN

In [4]:
abiotic_df["DATUMTIJDWAARDE"] = pd.to_datetime(abiotic_df["DATUMTIJDWAARDE"], format='mixed')
abiotic_df["DATUMTIJDWAARDE"] = abiotic_df["DATUMTIJDWAARDE"].dt.date
abiotic_df

,LOC_CODE,DATUMTIJDWAARDE,ZS,ZICHT,T,SiO2,SALNTT,PO4,pH,NO3,NO2,NH4,E,CHLFa
0,DANTZGT,2000-01-10,26.0,NaN,NaN,12.428571,NaN,1.483871,NaN,1.142857,1.000000,9.500000,NaN,8.00
1,DANTZGT,2002-01-10,NaN,10.0,15.170,NaN,31.18,NaN,8.060,NaN,NaN,NaN,NaN,NaN
2,DANTZGT,2003-01-10,89.0,5.0,13.250,5.821429,33.03,1.354839,8.130,1.214286,0.714286,9.142857,3.23678,20.60
3,DANTZGT,2009-01-10,NaN,NaN,15.000,NaN,31.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,DANTZGT,2010-01-10,160.0,3.0,12.400,18.928571,28.90,0.806452,8.000,3.571429,1.642857,15.714286,4.61000,16.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15288,WALCRN70,1992-09-04,5.0,NaN,7.900,0.500000,35.31,0.080645,8.300,3.642857,0.071429,0.642857,NaN,4.64
15289,WALCRN70,2001-09-04,6.0,NaN,8.338,1.035714,34.67,0.129032,8.227,3.142857,0.142857,0.142857,NaN,9.20
15290,WALCRN70,1994-09-06,2.0,NaN,12.100,0.321429,34.83,0.709677,8.500,0.178571,0.035714,0.285714,NaN,2.60
15291,WALCRN70,1999-09-08,2.0,NaN,18.120,1.250000,35.08,0.129032,7.989,0.107143,0.214286,0.500000,NaN,1.18
15292,WALCRN70,1999-09-08,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.25350,NaN

In [5]:
biotic_df["DATUMTIJDWAARDE"] = pd.to_datetime(biotic_df["DATUMTIJDWAARDE"], format='mixed')
biotic_df["DATUMTIJDWAARDE"] = biotic_df["DATUMTIJDWAARDE"].dt.date
biotic_df

,LOC_CODE,DATUMTIJDWAARDE,Acn,Aco,Ata,Agl,Cfu,Ccu,Cda,Cdeb,...,Rst,Rte,Stu,Tni,Tec,Tle,Tno,Tro,Tor,Dat
0,DANTZGT,1990-04-04,NaN,NaN,NaN,3.271842,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,4.669596,3.572755,3.572755,NaN,4.475787,NaN,NaN
1,DANTZGT,1990-04-24,NaN,NaN,NaN,4.590418,NaN,NaN,NaN,NaN,...,NaN,NaN,2.448706,3.447933,NaN,NaN,NaN,3.447933,NaN,NaN
2,DANTZGT,1990-05-09,NaN,NaN,NaN,4.669596,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.012035,1.973128,NaN
3,DANTZGT,1990-05-23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3.590842,NaN,NaN
4,DANTZGT,1990-06-07,NaN,NaN,2.267172,5.300487,2.444045,NaN,NaN,NaN,...,NaN,NaN,NaN,3.566909,1.968483,3.442009,NaN,3.496376,1.968483,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11058,WALCRN70,2019-06-13,NaN,2.034717,NaN,2.333737,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.809514,NaN,NaN,NaN,NaN,2.333737,NaN
11059,WALCRN70,2019-07-15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.961517,NaN
11060,WALCRN70,2019-08-15,NaN,2.008643,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.959085,NaN,NaN,NaN,NaN,3.004795,NaN
11061,WALCRN70,2019-09-12,NaN,NaN,NaN,NaN,NaN,2.980947,3.032049,2.980947,...,NaN,NaN,NaN,2.380246,NaN,NaN,NaN,NaN,3.281750,NaN
11062,WALCRN70,2019-10-30,NaN,NaN,NaN,2.708511,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,2.854396,NaN,NaN,NaN,2.611813,3.905874,NaN

In [6]:
abiotic_measurements = list(zip(abiotic_df["LOC_CODE"], abiotic_df["DATUMTIJDWAARDE"]))
biotic_measurements = list(zip(biotic_df["LOC_CODE"], biotic_df["DATUMTIJDWAARDE"]))


similarity = []
for abiotic in abiotic_measurements:
    for biotic in biotic_measurements:
        if abiotic[0] == biotic[0]:  # Check if locations are the same
            if abs((abiotic[1] - biotic[1]).days) <= 1:  # Check if dates are within one week
                similarity.append(abiotic)
                break

print(" abiotic measurements = ", len(abiotic_measurements), '\n', 
      "biotic measurements = ", len(biotic_measurements), '\n',
      "similarity = ", len(similarity))

similarity

 abiotic measurements =  15293
 biotic measurements =  11063
 similarity =  8987

[('DANTZGT', datetime.date(2002, 1, 10)),
 ('DANTZGT', datetime.date(2002, 10, 1)),
 ('DANTZGT', datetime.date(2001, 10, 10)),
 ('DANTZGT', datetime.date(2006, 10, 2)),
 ('DANTZGT', datetime.date(2006, 10, 2)),
 ('DANTZGT', datetime.date(2006, 10, 2)),
 ('DANTZGT', datetime.date(2006, 10, 2)),
 ('DANTZGT', datetime.date(1999, 10, 3)),
 ('DANTZGT', datetime.date(1999, 10, 5)),
 ('DANTZGT', datetime.date(1999, 10, 5)),
 ('DANTZGT', datetime.date(1999, 10, 5)),
 ('DANTZGT', datetime.date(1999, 10, 5)),
 ('DANTZGT', datetime.date(2005, 11, 10)),
 ('DANTZGT', datetime.date(1992, 11, 11)),
 ('DANTZGT', datetime.date(1997, 11, 11)),
 ('DANTZGT', datetime.date(1997, 11, 11)),
 ('DANTZGT', datetime.date(1997, 11, 11)),
 ('DANTZGT', datetime.date(1997, 11, 11)),
 ('DANTZGT', datetime.date(2003, 11, 11)),
 ('DANTZGT', datetime.date(2003, 11, 11)),
 ('DANTZGT', datetime.date(2003, 11, 11)),
 ('DANTZGT', datetime.date(2003, 11, 11)),
 ('DANTZGT', datetime.date(2004, 11, 11)),
 ('DANTZGT', datetime.date(2004, 11, 11)),
 ('DANTZGT', datetime.date(2004, 11, 11)),
 ('DANTZGT', datetime.date(2004, 11, 11)),
 ('DANTZGT', datetime.date(2005, 11, 11)),
 ('DANTZGT', datetime.date(2005, 11, 11)),
 ('DANTZGT', datetime.date(2005, 11, 11)),
 ('DANTZGT', datetime.date(2005, 11, 11)),
 ('DANTZGT', datetime.date(1998, 11, 12)),
 ('DANTZGT', datetime.date(2001, 11, 12)),
 ('DANTZGT', datetime.date(2008, 12, 11)),
 ('DANTZGT', datetime.date(1990, 12, 12)),
 ('DANTZGT', datetime.date(2002, 12, 12)),
 ('DANTZGT', datetime.date(2006, 12, 12)),
 ('DANTZGT', datetime.date(2007, 12, 12)),
 ('DANTZGT', datetime.date(2008, 12, 12)),
 ('DANTZGT', datetime.date(2004, 12, 5)),
 ('DANTZGT', datetime.date(2004, 12, 5)),
 ('DANTZGT', datetime.date(2004, 12, 5)),
 ('DANTZGT', datetime.date(2004, 12, 5)),
 ('DANTZGT', datetime.date(1992, 12, 8)),
 ('DANTZGT', datetime.date(1997, 12, 8)),
 ('DANTZGT', datetime.date(1997, 12, 8)),
 ('DANTZGT', datetime.date(1997, 12, 8)),
 ('DANTZGT', datetime.date(1997, 12, 8)),
 ('DANTZGT', datetime.date(1993, 10, 13)),
 ('DANTZGT', datetime.date(2004, 10, 13)),
 ('DANTZGT', datetime.date(1998, 11, 13)),
 ('DANTZGT', datetime.date(1998, 11, 13)),
 ('DANTZGT', datetime.date(1998, 11, 13)),
 ('DANTZGT', datetime.date(1998, 11, 13)),
 ('DANTZGT', datetime.date(2001, 11, 13)),
 ('DANTZGT', datetime.date(2001, 11, 13)),
 ('DANTZGT', datetime.date(2001, 11, 13)),
 ('DANTZGT', datetime.date(2001, 11, 13)),
 ('DANTZGT', datetime.date(2002, 11, 13)),
 ('DANTZGT', datetime.date(2002, 11, 13)),
 ('DANTZGT', datetime.date(2002, 11, 13)),
 ('DANTZGT', datetime.date(2002, 11, 13)),
 ('DANTZGT', datetime.date(2010, 12, 13)),
 ('DANTZGT', datetime.date(2006, 3, 13)),
 ('DANTZGT', datetime.date(2007, 3, 13)),
 ('DANTZGT', datetime.date(2005, 4, 13)),
 ('DANTZGT', datetime.date(2006, 4, 13)),
 ('DANTZGT', datetime.date(1992, 5, 13)),
 ('DANTZGT', datetime.date(2003, 5, 13)),
 ('DANTZGT', datetime.date(2003, 5, 13)),
 ('DANTZGT', datetime.date(2003, 5, 13)),
 ('DANTZGT', datetime.date(2003, 5, 13)),
 ('DANTZGT', datetime.date(1997, 6, 13)),
 ('DANTZGT', datetime.date(2005, 6, 13)),
 ('DANTZGT', datetime.date(2016, 7, 13)),
 ('DANTZGT', datetime.date(2009, 8, 13)),
 ('DANTZGT', datetime.date(2002, 9, 13)),
 ('DANTZGT', datetime.date(2006, 9, 13)),
 ('DANTZGT', datetime.date(2016, 9, 13)),
 ('DANTZGT', datetime.date(2003, 1, 14)),
 ('DANTZGT', datetime.date(2004, 1, 14)),
 ('DANTZGT', datetime.date(1998, 10, 14)),
 ('DANTZGT', datetime.date(2008, 10, 14)),
 ('DANTZGT', datetime.date(1990, 11, 14)),
 ('DANTZGT', datetime.date(1995, 2, 14)),
 ('DANTZGT', datetime.date(1995, 2, 14)),
 ('DANTZGT', datetime.date(1995, 2, 14)),
 ('DANTZGT', datetime.date(1995, 2, 14)),
 ('DANTZGT', datetime.date(1991, 3, 14)),
 ('DANTZGT', datetime.date(2000, 3, 14)),
 ('DANTZGT', datetime.date(2016, 3, 14)),
 ('DANTZGT', datetime.date(2019, 3, 14)),
 ('DANTZGT', datetime.date(1997, 4, 14)),
 ('DANTZGT', datetime.date(2004, 4, 14)),
 ('DANTZGT', datetime.date(2004, 4, 14)),
 ('DANTZGT', datetime.date(2010, 4, 14)),
 ('DANTZGT', datetime.date(2016, 4, 14)),
 ('DANTZGT', datetime.date(1996, 5, 14)),
 ('DANTZGT', datetime.date(2008, 5, 14)),
 ('DANTZGT', datetime.date(2009, 5, 14)),
 ('DANTZGT', datetime.date(2001, 6, 14)),
 ('DANTZGT', datetime.date(1992, 7, 14)),
 ('DANTZGT', datetime.date(1995, 7, 14)),
 ('DANTZGT', datetime.date(2009, 7, 14)),
 ('DANTZGT', datetime.date(2017, 7, 14)),
 ('DANTZGT', datetime.date(1998, 8, 14)),
 ('DANTZGT', datetime.date(1998, 8, 14)),
 ('DANTZGT', datetime.date(1998, 8, 14)),
 ('DANTZGT', datetime.date(1998, 8, 14)),
 ('DANTZGT', datetime.date(2001, 8, 14)),
 ('DANTZGT', datetime.date(2001, 8, 14)),
 ('DANTZGT', datetime.date(2001, 8, 14)),
 ('DANTZGT', datetime.date(2001, 8, 14)),
 ('DANTZGT', datetime.date(2007, 8, 14)),
 ('DANTZGT', datetime.date(1998, 9, 14)),
 ('DANTZGT', datetime.date(2004, 9, 14)),
 ('DANTZGT', datetime.date(2005, 9, 14)),
 ('DANTZGT', datetime.date(2017, 9, 14)),
 ('DANTZGT', datetime.date(2008, 1, 15)),
 ('DANTZGT', datetime.date(2009, 1, 15)),
 ('DANTZGT', datetime.date(2010, 1, 15)),
 ('DANTZGT', datetime.date(2002, 10, 15)),
 ('DANTZGT', datetime.date(2003, 10, 15)),
 ('DANTZGT', datetime.date(2009, 10, 15)),
 ('DANTZGT', datetime.date(2006, 11, 15)),
 ('DANTZGT', datetime.date(1994, 12, 15)),
 ('DANTZGT', datetime.date(2003, 12, 15)),
 ('DANTZGT', datetime.date(2000, 2, 15)),
 ('DANTZGT', datetime.date(2000, 2, 15)),
 ('DANTZGT', datetime.date(2000, 2, 15)),
 ('DANTZGT', datetime.date(2000, 2, 15)),
 ('DANTZGT', datetime.date(2005, 2, 15)),
 ('DANTZGT', datetime.date(2005, 2, 15)),
 ('DANTZGT', datetime.date(2005, 2, 15)),
 ('DANTZGT', datetime.date(2005, 2, 15)),
 ('DANTZGT', datetime.date(1995, 3, 15)),
 ('DANTZGT', datetime.date(2012, 3, 15)),
 ('DANTZGT', datetime.date(2018, 3, 15)),
 ('DANTZGT', datetime.date(1991, 4, 15)),
 ('DANTZGT', datetime.date(1992, 4, 15)),
 ('DANTZGT', datetime.date(2009, 4, 15)),
 ('DANTZGT', datetime.date(2013, 4, 15)),
 ('DANTZGT', datetime.date(1991, 5, 15)),
 ('DANTZGT', datetime.date(1995, 5, 15)),
 ('DANTZGT', datetime.date(1995, 5, 15)),
 ('DANTZGT', datetime.date(1995, 5, 15)),
 ('DANTZGT', datetime.date(1995, 5, 15)),
 ('DANTZGT', datetime.date(1997, 5, 15)),
 ('DANTZGT', datetime.date(1997, 5, 15)),
 ('DANTZGT', datetime.date(1997, 5, 15)),
 ('DANTZGT', datetime.date(1997, 5, 15)),
 ('DANTZGT', datetime.date(2018, 5, 15)),
 ('DANTZGT', datetime.date(2017, 6, 15)),
 ('DANTZGT', datetime.date(1997, 7, 15)),
 ('DANTZGT', datetime.date(1998, 7, 15)),
 ('DANTZGT', datetime.date(2003, 7, 15)),
 ('DANTZGT', datetime.date(1990, 8, 15)),
 ('DANTZGT', datetime.date(2002, 8, 15)),
 ('DANTZGT', datetime.date(2002, 8, 15)),
 ('DANTZGT', datetime.date(2002, 8, 15)),
 ('DANTZGT', datetime.date(2002, 8, 15)),
 ('DANTZGT', datetime.date(2014, 8, 15)),
 ('DANTZGT', datetime.date(2017, 8, 15)),
 ('DANTZGT', datetime.date(1993, 9, 15)),
 ('DANTZGT', datetime.date(2008, 9, 15)),
 ('DANTZGT', datetime.date(1991, 1, 16)),
 ('DANTZGT', datetime.date(2009, 11, 16)),
 ('DANTZGT', datetime.date(2009, 12, 16)),
 ('DANTZGT', datetime.date(2001, 2, 16)),
 ('DANTZGT', datetime.date(2001, 2, 16)),
 ('DANTZGT', datetime.date(2001, 2, 16)),
 ('DANTZGT', datetime.date(2001, 2, 16)),
 ('DANTZGT', datetime.date(2007, 2, 16)),
 ('DANTZGT', datetime.date(2009, 2, 16)),
 ('DANTZGT', datetime.date(2004, 3, 16)),
 ('DANTZGT', datetime.date(2005, 3, 16)),
 ('DANTZGT', datetime.date(2017, 3, 16)),
 ('DANTZGT', datetime.date(1996, 4, 16)),
 ('DANTZGT', datetime.date(2001, 5, 16)),
 ('DANTZGT', datetime.date(2001, 5, 16)),
 ('DANTZGT', datetime.date(2001, 5, 16)),
 ('DANTZGT', datetime.date(2001, 5, 16)),
 ('DANTZGT', datetime.date(1993, 6, 16)),
 ('DANTZGT', datetime.date(2001, 7, 16)),
 ('DANTZGT', datetime.date(2010, 8, 16)),
 ('DANTZGT', datetime.date(2018, 8, 16)),
 ('DANTZGT', datetime.date(2010, 9, 16)),
 ('DANTZGT', datetime.date(1995, 1, 17)),
 ('DANTZGT', datetime.date(2000, 1, 17)),
 ('DANTZGT', datetime.date(2001, 1, 17)),
 ('DANTZGT', datetime.date(2005, 1, 17)),
 ('DANTZGT', datetime.date(1990, 10, 17)),
 ('DANTZGT', datetime.date(1993, 11, 17)),
 ('DANTZGT', datetime.date(1994, 11, 17)),
 ('DANTZGT', datetime.date(1994, 11, 17)),
 ('DANTZGT', datetime.date(1994, 11, 17)),
 ('DANTZGT', datetime.date(1994, 11, 17)),
 ('DANTZGT', datetime.date(1999, 12, 17)),
 ('DANTZGT', datetime.date(1997, 3, 17)),
 ('DANTZGT', datetime.date(2001, 4, 17)),
 ('DANTZGT', datetime.date(2020, 4, 17)),
 ('DANTZGT', datetime.date(2013, 5, 17)),
 ('DANTZGT', datetime.date(2017, 5, 17)),
 ('DANTZGT', datetime.date(1998, 6, 17)),
 ('DANTZGT', datetime.date(2010, 6, 17)),
 ('DANTZGT', datetime.date(2002, 7, 17)),
 ('DANTZGT', datetime.date(2006, 7, 17)),
 ('DANTZGT', datetime.date(2014, 9, 17)),
 ('DANTZGT', datetime.date(1999, 11, 18)),
 ('DANTZGT', datetime.date(1999, 11, 18)),
 ('DANTZGT', datetime.date(1999, 11, 18)),
 ('DANTZGT', datetime.date(1999, 11, 18)),
 ('DANTZGT', datetime.date(1997, 2, 18)),
 ('DANTZGT', datetime.date(1997, 2, 18)),
 ('DANTZGT', datetime.date(1997, 2, 18)),
 ('DANTZGT', datetime.date(1997, 2, 18)),
 ('DANTZGT', datetime.date(2010, 2, 18)),
 ('DANTZGT', datetime.date(1993, 5, 18)),
 ('DANTZGT', datetime.date(2015, 5, 18)),
 ('DANTZGT', datetime.date(1990, 7, 18)),
 ('DANTZGT', datetime.date(2014, 7, 18)),
 ('DANTZGT', datetime.date(1993, 8, 18)),
 ('DANTZGT', datetime.date(2007, 9, 18)),
 ('DANTZGT', datetime.date(2012, 9, 18)),
 ('DANTZGT', datetime.date(2015, 9, 18)),
 ('DANTZGT', datetime.date(2018, 9, 18)),
 ('DANTZGT', datetime.date(1999, 10, 19)),
 ('DANTZGT', datetime.date(1991, 12, 19)),
 ('DANTZGT', datetime.date(1992, 2, 19)),
 ('DANTZGT', datetime.date(2004, 2, 19)),
 ('DANTZGT', datetime.date(2010, 3, 19)),
 ('DANTZGT', datetime.date(2013, 3, 19)),
 ('DANTZGT', datetime.date(2020, 3, 19)),
 ('DANTZGT', datetime.date(2017, 4, 19)),
 ('DANTZGT', datetime.date(1998, 5, 19)),
 ('DANTZGT', datetime.date(1998, 5, 19)),
 ('DANTZGT', datetime.date(1998, 5, 19)),
 ('DANTZGT', datetime.date(1998, 5, 19)),
 ('DANTZGT', datetime.date(2006, 5, 19)),
 ('DANTZGT', datetime.date(2002, 6, 19)),
 ('DANTZGT', datetime.date(2006, 6, 19)),
 ('DANTZGT', datetime.date(2014, 6, 19)),
 ('DANTZGT', datetime.date(2018, 6, 19)),
 ('DANTZGT', datetime.date(1993, 7, 19)),
 ('DANTZGT', datetime.date(2018, 7, 19)),
 ('DANTZGT', datetime.date(1999, 8, 19)),
 ('DANTZGT', datetime.date(1999, 8, 19)),
 ('DANTZGT', datetime.date(1999, 8, 19)),
 ('DANTZGT', datetime.date(1999, 8, 19)),
 ('DANTZGT', datetime.date(1990, 9, 19)),
 ('DANTZGT', datetime.date(1994, 9, 19)),
 ('DANTZGT', datetime.date(2019, 9, 19)),
 ('DANTZGT', datetime.date(2006, 2, 10)),
 ('DANTZGT', datetime.date(1998, 2, 6)),
 ('DANTZGT', datetime.date(1999, 2, 9)),
 ('DANTZGT', datetime.date(2000, 10, 20)),
 ('DANTZGT', datetime.date(2000, 12, 20)),
 ('DANTZGT', datetime.date(2001, 3, 20)),
 ('DANTZGT', datetime.date(1993, 4, 20)),
 ('DANTZGT', datetime.date(1999, 5, 20)),
 ('DANTZGT', datetime.date(2003, 5, 20)),
 ('DANTZGT', datetime.date(1990, 6, 20)),
 ('DANTZGT', datetime.date(1994, 7, 20)),
 ('DANTZGT', datetime.date(1999, 7, 20)),
 ('DANTZGT', datetime.date(2015, 8, 20)),
 ('DANTZGT', datetime.date(1999, 9, 20)),
 ('DANTZGT', datetime.date(1992, 1, 21)),
 ('DANTZGT', datetime.date(1993, 1, 21)),
 ('DANTZGT', datetime.date(1996, 11, 21)),
 ('DANTZGT', datetime.date(1996, 11, 21)),
 ('DANTZGT', datetime.date(1996, 11, 21)),
 ('DANTZGT', datetime.date(1996, 11, 21)),
 ('DANTZGT', datetime.date(1993, 12, 21)),
 ('DANTZGT', datetime.date(1998, 4, 21)),
 ('DANTZGT', datetime.date(2000, 11, 22)),
 ('DANTZGT', datetime.date(2000, 11, 22)),
 ('DANTZGT', datetime.date(2000, 11, 22)),
 ('DANTZGT', datetime.date(2000, 11, 22)),
 ('DANTZGT', datetime.date(2008, 2, 22)),
 ('DANTZGT', datetime.date(2008, 2, 22)),
 ('DANTZGT', datetime.date(2002, 3, 22)),
 ('DANTZGT', datetime.date(2002, 5, 22)),
 ('DANTZGT', datetime.date(2002, 5, 22)),
 ('DANTZGT', datetime.date(2002, 5, 22)),
 ('DANTZGT', datetime.date(2002, 5, 22)),
 ('DANTZGT', datetime.date(2012, 5, 22)),
 ('DANTZGT', datetime.date(1994, 6, 22)),
 ('DANTZGT', datetime.date(1999, 6, 22)),
 ('DANTZGT', datetime.date(2011, 6, 22)),
 ('DANTZGT', datetime.date(2006, 7, 22)),
 ('DANTZGT', datetime.date(1994, 8, 22)),
 ('DANTZGT', datetime.date(1994, 8, 22)),
 ('DANTZGT', datetime.date(1994, 8, 22)),
 ('DANTZGT', datetime.date(1994, 8, 22)),
 ('DANTZGT', datetime.date(2000, 8, 22)),
 ('DANTZGT', datetime.date(2005, 8, 22)),
 ('DANTZGT', datetime.date(2005, 8, 22)),
 ('DANTZGT', datetime.date(2005, 8, 22)),
 ('DANTZGT', datetime.date(2005, 8, 22)),
 ('DANTZGT', datetime.date(2011, 8, 22)),
 ('DANTZGT', datetime.date(1997, 9, 22)),
 ('DANTZGT', datetime.date(1999, 2, 23)),
 ('DANTZGT', datetime.date(1992, 3, 23)),
 ('DANTZGT', datetime.date(1999, 4, 23)),
 ('DANTZGT', datetime.date(2002, 4, 23)),
 ('DANTZGT', datetime.date(2003, 4, 23)),
 ('DANTZGT', datetime.date(2007, 5, 23)),
 ('DANTZGT', datetime.date(2007, 7, 23)),
 ('DANTZGT', datetime.date(2012, 8, 23)),
 ('DANTZGT', datetime.date(1992, 9, 23)),
 ('DANTZGT', datetime.date(1997, 9, 23)),
 ('DANTZGT', datetime.date(2011, 2, 24)),
 ('DANTZGT', datetime.date(1998, 3, 24)),
 ('DANTZGT', datetime.date(2007, 4, 24)),
 ('DANTZGT', datetime.date(2014, 4, 24)),
 ('DANTZGT', datetime.date(2015, 4, 24)),
 ('DANTZGT', datetime.date(1992, 6, 24)),
 ('DANTZGT', datetime.date(2003, 6, 24)),
 ('DANTZGT', datetime.date(1995, 8, 24)),
 ('DANTZGT', datetime.date(1995, 8, 24)),
 ('DANTZGT', datetime.date(1995, 8, 24)),
 ('DANTZGT', datetime.date(2001, 8, 24)),
 ('DANTZGT', datetime.date(2007, 10, 25)),
 ('DANTZGT', datetime.date(1991, 11, 25)),
 ('DANTZGT', datetime.date(2014, 2, 25)),
 ('DANTZGT', datetime.date(2003, 3, 25)),
 ('DANTZGT', datetime.date(2014, 3, 25)),
 ('DANTZGT', datetime.date(1994, 4, 25)),
 ('DANTZGT', datetime.date(2008, 4, 25)),
 ('DANTZGT', datetime.date(2018, 4, 25)),
 ('DANTZGT', datetime.date(2019, 4, 25)),
 ('DANTZGT', datetime.date(2010, 6, 25)),
 ('DANTZGT', datetime.date(2019, 6, 25)),
 ('DANTZGT', datetime.date(2020, 6, 25)),
 ('DANTZGT', datetime.date(2000, 7, 25)),
 ('DANTZGT', datetime.date(2019, 7, 25)),
 ('DANTZGT', datetime.date(2005, 8, 25)),
 ('DANTZGT', datetime.date(1996, 9, 25)),
 ('DANTZGT', datetime.date(2001, 9, 25)),
 ('DANTZGT', datetime.date(1994, 1, 26)),
 ('DANTZGT', datetime.date(2001, 10, 26)),
 ('DANTZGT', datetime.date(2004, 10, 26)),
 ('DANTZGT', datetime.date(2003, 2, 26)),
 ('DANTZGT', datetime.date(2019, 2, 26)),
 ('DANTZGT', datetime.date(2007, 3, 26)),
 ('DANTZGT', datetime.date(2000, 4, 26)),
 ('DANTZGT', datetime.date(2006, 4, 26)),
 ('DANTZGT', datetime.date(2006, 4, 26)),
 ('DANTZGT', datetime.date(2011, 4, 26)),
 ('DANTZGT', datetime.date(1992, 5, 26)),
 ('DANTZGT', datetime.date(1994, 5, 26)),
 ('DANTZGT', datetime.date(2004, 5, 26)),
 ('DANTZGT', datetime.date(2011, 5, 26)),
 ('DANTZGT', datetime.date(2000, 6, 26)),
 ('DANTZGT', datetime.date(2008, 6, 26)),
 ('DANTZGT', datetime.date(2015, 6, 26)),
 ('DANTZGT', datetime.date(2018, 6, 26)),
 ('DANTZGT', datetime.date(2001, 7, 26)),
 ('DANTZGT', datetime.date(2011, 7, 26)),
 ('DANTZGT', datetime.date(2012, 7, 26)),
 ('DANTZGT', datetime.date(2016, 7, 26)),
 ('DANTZGT', datetime.date(2018, 7, 26)),
 ('DANTZGT', datetime.date(1992, 8, 26)),
 ('DANTZGT', datetime.date(1997, 8, 26)),
 ('DANTZGT', datetime.date(2004, 8, 26)),
 ('DANTZGT', datetime.date(2000, 9, 26)),
 ('DANTZGT', datetime.date(2007, 2, 27)),
 ('DANTZGT', datetime.date(2018, 2, 27)),
 ('DANTZGT', datetime.date(2015, 3, 27)),
 ('DANTZGT', datetime.date(2018, 3, 27)),
 ('DANTZGT', datetime.date(2004, 4, 27)),
 ('DANTZGT', datetime.date(2004, 4, 27)),
 ('DANTZGT', datetime.date(2010, 4, 27)),
 ('DANTZGT', datetime.date(2012, 4, 27)),
 ('DANTZGT', datetime.date(2015, 5, 27)),
 ('DANTZGT', datetime.date(2019, 5, 27)),
 ('DANTZGT', datetime.date(1996, 6, 27)),
 ('DANTZGT', datetime.date(2001, 6, 27)),
 ('DANTZGT', datetime.date(2007, 6, 27)),
 ('DANTZGT', datetime.date(2012, 6, 27)),
 ('DANTZGT', datetime.date(2020, 7, 27)),
 ('DANTZGT', datetime.date(1993, 8, 27)),
 ('DANTZGT', datetime.date(2007, 8, 27)),
 ('DANTZGT', datetime.date(2013, 8, 27)),
 ('DANTZGT', datetime.date(2004, 9, 27)),
 ('DANTZGT', datetime.date(2005, 10, 28)),
 ('DANTZGT', datetime.date(2000, 3, 28)),
 ('DANTZGT', datetime.date(2019, 3, 28)),
 ('DANTZGT', datetime.date(1992, 4, 28)),
 ('DANTZGT', datetime.date(1997, 5, 28)),
 ('DANTZGT', datetime.date(2008, 5, 28)),
 ('DANTZGT', datetime.date(2010, 5, 28)),
 ('DANTZGT', datetime.date(2020, 5, 28)),
 ('DANTZGT', datetime.date(2005, 6, 28)),
 ('DANTZGT', datetime.date(2013, 6, 28)),
 ('DANTZGT', datetime.date(2016, 6, 28)),
 ('DANTZGT', datetime.date(1992, 7, 28)),
 ('DANTZGT', datetime.date(1997, 7, 28)),
 ('DANTZGT', datetime.date(2004, 7, 28)),
 ('DANTZGT', datetime.date(2017, 7, 28)),
 ('DANTZGT', datetime.date(1996, 8, 28)),
 ('DANTZGT', datetime.date(1996, 8, 28)),
 ('DANTZGT', datetime.date(1996, 8, 28)),
 ('DANTZGT', datetime.date(1996, 8, 28)),
 ('DANTZGT', datetime.date(1993, 9, 28)),
 ('DANTZGT', datetime.date(1998, 9, 28)),
 ('DANTZGT', datetime.date(2002, 10, 29)),
 ('DANTZGT', datetime.date(2008, 10, 29)),
 ('DANTZGT', datetime.date(2008, 2, 29)),
 ('DANTZGT', datetime.date(1994, 3, 29)),
 ('DANTZGT', datetime.date(1994, 3, 29)),
 ('DANTZGT', datetime.date(1994, 3, 29)),
 ('DANTZGT', datetime.date(1994, 3, 29)),
 ('DANTZGT', datetime.date(1999, 3, 29)),
 ('DANTZGT', datetime.date(2006, 3, 29)),
 ('DANTZGT', datetime.date(2012, 3, 29)),
 ('DANTZGT', datetime.date(1997, 4, 29)),
 ('DANTZGT', datetime.date(1997, 4, 29)),
 ('DANTZGT', datetime.date(2005, 4, 29)),
 ('DANTZGT', datetime.date(2016, 4, 29)),
 ('DANTZGT', datetime.date(2020, 4, 29)),
 ('DANTZGT', datetime.date(2000, 5, 29)),
 ('DANTZGT', datetime.date(2001, 5, 29)),
 ('DANTZGT', datetime.date(2012, 5, 29)),
 ('DANTZGT', datetime.date(2013, 5, 29)),
 ('DANTZGT', datetime.date(1998, 6, 29)),
 ('DANTZGT', datetime.date(1993, 7, 29)),
 ('DANTZGT', datetime.date(2003, 7, 29)),
 ('DANTZGT', datetime.date(2019, 8, 29)),
 ('DANTZGT', datetime.date(2005, 9, 29)),
 ('DANTZGT', datetime.date(2009, 3, 11)),
 ('DANTZGT', datetime.date(2020, 3, 3)),
 ('DANTZGT', datetime.date(2002, 3, 7)),
 ('DANTZGT', datetime.date(1997, 1, 30)),
 ('DANTZGT', datetime.date(1998, 10, 30)),
 ('DANTZGT', datetime.date(2010, 3, 30)),
 ('DANTZGT', datetime.date(2016, 3, 30)),
 ('DANTZGT', datetime.date(2020, 3, 30)),
 ('DANTZGT', datetime.date(1996, 5, 30)),
 ('DANTZGT', datetime.date(1996, 5, 30)),
 ('DANTZGT', datetime.date(1996, 5, 30)),
 ('DANTZGT', datetime.date(1996, 5, 30)),
 ('DANTZGT', datetime.date(2016, 5, 30)),
 ('DANTZGT', datetime.date(1993, 6, 30)),
 ('DANTZGT', datetime.date(1997, 6, 30)),
 ('DANTZGT', datetime.date(2004, 6, 30)),
 ('DANTZGT', datetime.date(2004, 6, 30)),
 ('DANTZGT', datetime.date(2017, 6, 30)),
 ('DANTZGT', datetime.date(1996, 7, 30)),
 ('DANTZGT', datetime.date(2013, 7, 30)),
 ('DANTZGT', datetime.date(2002, 8, 30)),
 ('DANTZGT', datetime.date(2006, 8, 30)),
 ('DANTZGT', datetime.date(2010, 8, 30)),
 ('DANTZGT', datetime.date(2016, 8, 30)),
 ('DANTZGT', datetime.date(2017, 8, 30)),
 ('DANTZGT', datetime.date(2008, 9, 30)),
 ('DANTZGT', datetime.date(2009, 9, 30)),
 ('DANTZGT', datetime.date(2003, 10, 31)),
 ('DANTZGT', datetime.date(2004, 3, 31)),
 ('DANTZGT', datetime.date(2004, 3, 31)),
 ('DANTZGT', datetime.date(2005, 3, 31)),
 ('DANTZGT', datetime.date(2008, 3, 31)),
 ('DANTZGT', datetime.date(2005, 5, 31)),
 ('DANTZGT', datetime.date(2017, 5, 31)),
 ('DANTZGT', datetime.date(1998, 7, 31)),
 ('DANTZGT', datetime.date(2002, 7, 31)),
 ('DANTZGT', datetime.date(2008, 7, 31)),
 ('DANTZGT', datetime.date(1999, 4, 10)),
 ('DANTZGT', datetime.date(1990, 4, 4)),
 ('DANTZGT', datetime.date(2011, 4, 4)),
 ('DANTZGT', datetime.date(1994, 4, 8)),
 ('DANTZGT', datetime.date(1999, 4, 8)),
 ('DANTZGT', datetime.date(2014, 4, 8)),
 ('DANTZGT', datetime.date(2015, 4, 9)),
 ('DANTZGT', datetime.date(2018, 4, 9)),

In [7]:
dups = abiotic_df.loc[abiotic_df[["LOC_CODE", "DATUMTIJDWAARDE"]].duplicated(keep=False)]

In [8]:
dups = dups.sort_values(by=["LOC_CODE", "DATUMTIJDWAARDE"])
display(dups)

,LOC_CODE,DATUMTIJDWAARDE,ZS,ZICHT,T,SiO2,SALNTT,PO4,pH,NO3,NO2,NH4,E,CHLFa
589,DANTZGT,1994-03-29,158.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
590,DANTZGT,1994-03-29,411.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,44.50
591,DANTZGT,1994-03-29,84.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
592,DANTZGT,1994-03-29,74.0,2.0,7.90,19.571429,27.03,0.548387,8.000,63.928571,1.357143,2.071429,NaN,27.20
465,DANTZGT,1994-08-22,63.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14910,WALCRN70,2006-11-10,4.7,NaN,NaN,1.785714,NaN,0.129032,NaN,0.107143,0.035714,0.071429,NaN,2.14
15028,WALCRN70,2006-11-15,NaN,NaN,14.13,NaN,35.09,NaN,7.917,NaN,NaN,NaN,NaN,NaN
15029,WALCRN70,2006-11-15,3.4,NaN,NaN,1.500000,NaN,0.258065,NaN,0.714286,0.035714,0.714286,NaN,1.58
15177,WALCRN70,2006-12-20,NaN,NaN,11.93,NaN,35.28,NaN,7.852,NaN,NaN,NaN,NaN,NaN
15178,WALCRN70,2006-12-20,4.3,NaN,NaN,4.535714,NaN,0.451613,NaN,7.071429,0.142857,0.071429,NaN,0.58

In [9]:


def custom_aggregate(series):
    if series.notna().any():
        return series.mean()
    return None

# Identify the columns that need aggregation
agg_columns = abiotic_df.columns.difference(['LOC_CODE', 'DATUMTIJDWAARDE'])

# Create the aggregation dictionary
agg_functions = {col: custom_aggregate for col in agg_columns}

abiotic_agregated = dups.groupby(["LOC_CODE", "DATUMTIJDWAARDE"]).agg(agg_functions).reset_index()

abiotic_agregated["AGG"] = True

In [10]:
abiotic_deduped = abiotic_df.drop_duplicates(subset=["LOC_CODE", "DATUMTIJDWAARDE"], keep=False)
abiotic_deduped["AGG"] = False

abiotic_updated = pd.concat([abiotic_deduped, abiotic_agregated], ignore_index=True)

abiotic_updated

C:\Users\rijkj\AppData\Local\Temp\ipykernel_26676\2414470699.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  abiotic_deduped["AGG"] = False

,LOC_CODE,DATUMTIJDWAARDE,ZS,ZICHT,T,SiO2,SALNTT,PO4,pH,NO3,NO2,NH4,E,CHLFa,AGG
0,DANTZGT,2000-01-10,26.0,NaN,NaN,12.428571,NaN,1.483871,NaN,1.142857,1.000000,9.500000,NaN,8.00,False
1,DANTZGT,2002-01-10,NaN,10.0,15.17,NaN,31.18,NaN,8.060,NaN,NaN,NaN,NaN,NaN,False
2,DANTZGT,2003-01-10,89.0,5.0,13.25,5.821429,33.03,1.354839,8.130,1.214286,0.714286,9.142857,3.23678,20.60,False
3,DANTZGT,2009-01-10,NaN,NaN,15.00,NaN,31.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,False
4,DANTZGT,2010-01-10,160.0,3.0,12.40,18.928571,28.90,0.806452,8.000,3.571429,1.642857,15.714286,4.61000,16.00,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13606,WALCRN70,2006-07-20,1.2,NaN,16.77,0.607143,34.90,0.064516,8.247,0.107143,0.035714,0.071429,0.16800,0.80,True
13607,WALCRN70,2006-09-14,3.2,NaN,18.47,0.500000,34.91,0.129032,9.482,0.107143,0.035714,0.071429,NaN,2.24,True
13608,WALCRN70,2006-11-10,4.7,NaN,17.41,1.785714,35.08,0.129032,7.996,0.107143,0.035714,0.071429,NaN,2.14,True
13609,WALCRN70,2006-11-15,3.4,NaN,14.13,1.500000,35.09,0.258065,7.917,0.714286,0.035714,0.714286,NaN,1.58,True
13610,WALCRN70,2006-12-20,4.3,NaN,11.93,4.535714,35.28,0.451613,7.852,7.071429,0.142857,0.071429,NaN,0.58,True

### Check if duplicates are now gone

In [11]:
abiotic_updated.loc[abiotic_updated[["LOC_CODE", "DATUMTIJDWAARDE"]].duplicated(keep=False)].sort_values(by=["LOC_CODE", "DATUMTIJDWAARDE"])

Empty DataFrame
Columns: [LOC_CODE, DATUMTIJDWAARDE, ZS, ZICHT, T, SiO2, SALNTT, PO4, pH, NO3, NO2, NH4, E, CHLFa, AGG]
Index: []

### Now perform all this on the phyto data

In [12]:
abiotic_updated = abiotic_updated.sort_values(by=["LOC_CODE", "DATUMTIJDWAARDE"])

filename = '../data/ABIO.xlsx'
sheetname = 'ABIO_AGGREGATED'

with pd.ExcelWriter(filename, mode='a') as writer:  
    abiotic_updated.to_excel(writer, sheet_name=sheetname, index=False)

print(f"Data written to sheet '{sheetname}' in '{filename}'")

Data written to sheet 'ABIO_AGGREGATED' in '../data/ABIO.xlsx'

In [13]:
biotic_df = biotic_df.sort_values(by=["LOC_CODE", "DATUMTIJDWAARDE"])

filename = '../data/PHYTO.xlsx'
sheetname = 'PHYTO_ONDATE'

with pd.ExcelWriter(filename, mode='a') as writer:  
    biotic_df.to_excel(writer, sheet_name=sheetname, index=False)

print(f"Data written to sheet '{sheetname}' in '{filename}'")

Data written to sheet 'PHYTO_ONDATE' in '../data/PHYTO.xlsx'

### Merge datasets on time TODO

In [1]:
# abiotic_grouped = abiotic_agregated.groupby(by="LOC_CODE")

# combined_dataset = pd.DataFrame()

# for location, group in abiotic_grouped:
#     biotic_loc = biotic_df.loc[biotic_df["LOC_CODE"] == location]
#     biotic_loc["MEASURED_DATE"] = biotic_loc["DATUMTIJDWAARDE"]
    

#     biotic_loc["DATUMTIJDWAARDE"] = pd.to_datetime(biotic_loc["DATUMTIJDWAARDE"])
#     group["DATUMTIJDWAARDE"] = pd.to_datetime(group["DATUMTIJDWAARDE"])

    
#     merged_group = pd.merge_asof(biotic_loc, group, on="DATUMTIJDWAARDE", direction='backward')
#     print(len(biotic_loc), len(group), len(merged_group))
#     combined_dataset = pd.concat([combined_dataset, merged_group], ignore_index=True)

# combined_dataset